### ISSUE TITLE
Support >=vulkan-headers-1.2.170 (vulkan_core.h:7839: error: syntax error before LL)

### ISSUE THREAD

**Issue by ionenwks** [quakeforge/quakeforge#13]
Changes in vulkan_core.h since ~vulkan-headers-1.2.170 seem to cause issues for qfcc:

With 1.2.179:
```
./qfcc -qq -O -g -Werror -Wall -Wno-integer-divide --no-default-paths -I. -I./ruamoko/include -I./include -MT ruamoko/scheme/Lexer.o -MD -MP -MF $depbase.Tqo -c -o ruamoko/scheme/Lexer.o ruamoko/scheme/Lexer.r &&\
sed -i -e '1s@:@: qfcc@' $depbase.Tqo &&\
mv -f $depbase.Tqo $depbase.Qo
In file included from /usr/include/vulkan/vulkan.h:11:
In file included from libs/video/renderer/vulkan/vkgen/vulkan.r:2:
/usr/include/vulkan/vulkan_core.h: At top level:
/usr/include/vulkan/vulkan_core.h:7839: error: syntax error before LL
/usr/include/vulkan/vulkan_core.h:7840: error: syntax error before LL
[...]
```

line 7839-7840:
```
static const VkPipelineStageFlagBits2KHR VK_PIPELINE_STAGE_2_NONE_KHR = 0ULL;
static const VkPipelineStageFlagBits2KHR VK_PIPELINE_STAGE_2_TOP_OF_PIPE_BIT_KHR = 0x00000001ULL;
```

Perhaps earlier'ish headers have issues too, but tested to build fine with vulkan-headers-1.2.162

**Comment by taniwha** [comment]
Yeah, I have 162 on my system. I'll look into getting 179 or so ASAP.

**Comment by ionenwks** [comment]
Thanks, gave it a try and vulkan seems fine with new headers.

**Comment by taniwha** [comment]
Yeah, the problem was qfcc doesn't actually support 64-bit ints (yet). Since I gave it doubles (64-bit float) a while back, it should be trivial to do so, though. However, in the meantime, at least it won't error out when parsing the vulkan headers (needed for generating the parser code for the plist-based vulkan pipeline/renderpass configuration).
